{{- range $name, $config := .Values.workloads }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "techx.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  {{- with $config.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $config.automountServiceAccountToken }}
{{- end }}

